services:
  frontend:
    image: frontend
    build: frontend
    networks:
      - frontend
    volumes:
      - ./frontend/app:/app

  frontend-prod:
    image: nginx:alpine
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    networks:
      - frontend
#   ports:
#     - 8088:80

  api:
    image: api
    build:
      context: api
      args: []
#       - PORT=5000
    networks:
      - frontend
      - backend
    volumes:
      - ./api:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - BACKEND_URL=http://backend
    stop_signal: SIGINT


  backend:
    image: backend
    build:
      context: backend
      args: []
#       - PORT=5000
    networks:
      - backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    stop_signal: SIGINT



networks:
  frontend:
  backend:
